package _Root.patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = 'df670dfb-0b52-4cf7-ab82-30b8c7c9c289' (id = 'MySample')
in the project with uuid = '09bdce23-33ea-48e8-82fa-dbe4fbbb2c27', and delete the patch script.
*/
create(uuid("09bdce23-33ea-48e8-82fa-dbe4fbbb2c27"), Project({
    uuid = "df670dfb-0b52-4cf7-ab82-30b8c7c9c289"
    id("MySample")
    parentId("_Root")
    name = "MySample"
}))

