package _Root.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = '7611578c-f691-447c-a949-77da6d984c61' (id = 'MySample_Build')
in the project with uuid = 'df670dfb-0b52-4cf7-ab82-30b8c7c9c289', and delete the patch script.
*/
create(uuid("df670dfb-0b52-4cf7-ab82-30b8c7c9c289"), BuildType({
    uuid = "7611578c-f691-447c-a949-77da6d984c61"
    id("MySample_Build")
    name = "Build"

    vcs {
        root(AbsoluteId("MySample_HttpsGithubComRyu1knSandboxTeamcitySampleGitRefsHeadsMaster"))
    }

    steps {
        script {
            scriptContent = "./greet.sh"
        }
    }

    triggers {
        vcs {
        }
    }
}))

