package _Root.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = 'bdfc0196-b36a-420f-904d-a5b27118f661' (id = 'MySample_HttpsGithubComRyu1knSandboxTeamcitySampleGitRefsHeadsMaster')
in the project with uuid = 'df670dfb-0b52-4cf7-ab82-30b8c7c9c289', and delete the patch script.
*/
create(uuid("df670dfb-0b52-4cf7-ab82-30b8c7c9c289"), GitVcsRoot({
    uuid = "bdfc0196-b36a-420f-904d-a5b27118f661"
    id("MySample_HttpsGithubComRyu1knSandboxTeamcitySampleGitRefsHeadsMaster")
    name = "https://github.com/ryu1kn/sandbox--teamcity-sample.git#refs/heads/master"
    url = "https://github.com/ryu1kn/sandbox--teamcity-sample.git"
}))

